#!/bin/sh
PLATFORM=`uname -s`

FIX=2
if test -d libtool ; then
    if [ $PLATFORM = "OS/390" ] ; then
      # z/OS uses -z not -Z and doesn't exclude well so the tarball will have a few extra things in it
      tar -czf libtool-zOS-httpd-2.4-fix${FIX}.tar.Z libtool 
    fi
else
    echo "You aren't in the correct directory!"
    exit 1
fi
