#!/bin/sh
#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#
echo "libtoolize $*"
mydir=`pwd`
echo "libtoolize was invoked from directory $mydir"
if [ $# -eq 1 ]; then
  if [ $1 = "--version" ]; then
    echo "libtoolize (zlibtool pretending:) 1.5.26"
    exit 0
  fi
fi
ac_in_files="configure.in configure.ac"
ac_in=`ls $ac_in_files 2>/dev/null | head -1`
if [ x$ac_in = x ] ; then
  echo "libtoolize: couldn't find an autoconf input file: $ac_in_files" >&2
  exit 1
fi
auxdir_macro=`grep AC_CONFIG_AUX_DIR $ac_in`
auxdir=`echo $auxdir_macro | perl -pe 's/AC_CONFIG_AUX_DIR\(\[?(.*?)\]?\)/$1/'` 
lte=`libtool_printpath libtoolexe`
srcdir=`dirname $lte`
ln -sf $srcdir/../share/libtool/config.sub ./$auxdir/config.sub >/dev/null 2>&1
ln -sf $srcdir/../share/libtool/config.guess ./$auxdir/config.guess >/dev/null 2>&1
ln -sf $srcdir/libtool ./libtool >/dev/null 2>&1
ln -sf $srcdir/libtoolexe ./libtoolexe >/dev/null 2>&1
ln -sf $srcdir/ltconfig ./$auxdir/ltconfig >/dev/null 2>&1
ln -sf $srcdir/../share/aclocal/libtool.m4 build/libtool.m4
exit 0

