#!/bin/sh
#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#

echo "ltconfig $*"
mycwd=`pwd`
echo "ltconfig invoked from directory $mycwd"
lte=`libtool_printpath libtoolexe`
ltdir=`dirname $lte`
if test ".$1" = ".--output=shlibtool"
then
	if test -f ./shlibtool
	then
		echo "no need to create symbolic link to shlibtool"
	else
		echo "creating a symbolic link to shlibtool..."
		shlibtool="$ltdir/shlibtool"
		ln -s $shlibtool ./shlibtool
		ls -la ./shlibtool
	fi
else
	echo "#!/bin/sh" > libtool
	echo "$lte \$*" >> libtool
	chmod +x libtool
	if test -f ./ltconfig
	then
		echo "no need to create symbolic link to ltconfig"
	else
		real_ltconfig="$ltdir/ltconfig"
		ln -s $real_ltconfig ./ltconfig
		echo "just created this link from the current dir to $real_ltconfig:"
		ls -la ./ltconfig
	fi
fi

